name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install requests

      - name: Install build tools
        run: |
          pip install setuptools wheel

      - name: Run tests
        run: |
          pytest test.py

      - name: Package application
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-python-package
          path: |
            dist/*
