name: Python CI

# Trigger de Ejecución: Solo cuando se abra un Pull Request hacia la rama QA
on:
  pull_request:
    branches:
      - qa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Check out the repository
        uses: actions/checkout@v2

      # Paso 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Especifica la versión de Python que estás utilizando

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Asegúrate de que este archivo exista con tus dependencias

      # Paso 4: Ejecutar pruebas
      - name: Run tests
        run: |
          pytest  
